version: '3.9'

services:
  frontend:
    container_name: frontend
    env_file: 
      - ./src/frontend/.env
    restart: always
    build: ./src/frontend

  backend:
    container_name: backend
    restart: always
    build: ./src/backend
    ports:
      - "80:80"
