apiVersion: v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
  labels:
    name: backend
spec:
  selector:
    matchLabels:
      name: backend
    template:
      metadata:
        labels:
          name: backend
    spec:
      replicas: 2
      containers:
        - name: backend
          image: birkik8sacr.azurecr.io/backend:test
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          ports:
            - containerPort: 80
