apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
  labels:
    name: backend
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: backend
