apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: frontend
type: Opaque
data:
  DISCORD_TOKEN: "${DISCORD_TOKEN}"
  TEST_GUILD_ID: "${TEST_GUILD_ID}"
  CLIENT_ID: "${CLIENT_ID}"
