FROM node:stretch-slim

# create nonroot user
RUN adduser nonroot
RUN mkdir /home/app/ && chown -R nonroot:nonroot /home/app
WORKDIR /home/app

COPY --chown=nonroot:nonroot package-lock.json /home/app/
COPY --chown=nonroot:nonroot package.json /home/app/
RUN npm install

USER nonroot

COPY --chown=nonroot:nonroot register.js .
COPY --chown=nonroot:nonroot common/ common/
COPY --chown=nonroot:nonroot commands/ commands/
COPY --chown=nonroot:nonroot app.js .

ENTRYPOINT [ "node" ]
CMD [ "app.js" ]
