apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: prometheus
---
##### Comment the section below to disable the IP allowlist plugin #####
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ip-allowlist
  namespace: monitoring
config:
  allow:
    - 123.123.123.123/32 # Add your own IP here to allow just your own traffic
plugin: ip-restriction